declare module "remote/ButtonDesktop"
declare module "remote/ButtonMobile"
declare module "remote/Documents"
declare module "remote/DocumentDetail"
declare module "remote/DocumentDetailOptions"
declare module "base/App"
declare module "base/Bootstrap"